name: "tablettop_bot"
version: "0.1.0"
lang: "en"
timezone: "Europe/Paris"
antiflood:
  enabled: true
  time_window_seconds: 2
apps:
  - start
  - host_game
  - join_game
  - library
  - about
db:
  name: "tablettop_bot"
  tables:
    - users
    - events